variables:
  GIT_STRATEGY: none
  PACKAGE_WORKSPACE: "/var/tmp"

stages:
  - build
  - deploy
  - test


build_sle15sp5:
  tags:
    - sle15sp5
  stage: build
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH =~ /.*-sle15sp5/
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /.*-sle15sp5/
  script:
    - echo "Starting build stage for SLE15 SP5"
    - /root/bin/wait-for-publish.sh api.suse.de Devel:Virt:SLE-15-SP5:Staging libvirt SUSE_SLE-15-SP5_Update_standard x86_64
    - echo "Build stage finished"

deploy_sle15sp5:
  tags:
    - sle15sp5
  stage: deploy
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH =~ /.*-sle15sp5/
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /.*-sle15sp5/
  script:
    - echo "Starting deploy stage for SLE15 SP5"
    - /root/bin/deploy.sh virt_staging_repo https://download.suse.de/ibs/Devel:/Virt:/SLE-15-SP5:/Staging/SUSE_SLE-15-SP5_Update_standard/
    - echo "Deploy stage finished"

test_sle15sp5:
  tags:
    - sle15sp5
  stage: test
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH =~ /.*-sle15sp5/
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /.*-sle15sp5/
  script:
    - echo "Starting test stage for SLE15 SP5"
    - /root/bin/run-test.sh
    - echo "Test stage finished"


build_sle15sp6:
  tags:
    - sle15sp6
  stage: build
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH =~ /.*-sle15sp6/
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /.*-sle15sp6/
  script:
    - echo "Starting build stage for SLE15 SP6"
    - /root/bin/wait-for-publish.sh api.suse.de Devel:Virt:SLE-15-SP6:Staging libvirt SUSE_SLE-15-SP6_Update_standard x86_64
    - echo "Build stage finished"

deploy_sle15sp6:
  tags:
    - sle15sp6
  stage: deploy
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH =~ /.*-sle15sp6/
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /.*-sle15sp6/
  script:
    - echo "Starting deploy stage for SLE15 SP6"
    - /root/bin/deploy.sh virt_staging_repo https://download.suse.de/ibs/Devel:/Virt:/SLE-15-SP6:/Staging/SUSE_SLE-15-SP6_Update_standard/
    - echo "Deploy stage finished"

test_sle15sp6:
  tags:
    - sle15sp6
  stage: test
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH =~ /.*-sle15sp6/
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /.*-sle15sp6/
  script:
    - echo "Starting test stage for SLE15 SP6"
    - /root/bin/run-test.sh
    - echo "Test stage finished"
