variables:
  GIT_DEPTH: 200
  GIT_SUBMODULE_STRATEGY: recursive
  PACKAGE_WORKSPACE: "/var/tmp"

stages:
  - build
  - deploy
  - test


build_sle15sp5:
  tags:
    - sle15sp5
  stage: build
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH =~ /.*-sle15sp5/
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /.*-sle15sp5/
  script:
    - echo "Starting build stage for SLE15 SP5"
    - /root/bin/wait-for-publish.sh api.suse.de home:jfehlig:gitlab-ci libvirt SUSE_SLE-15-SP5_Update_standard x86_64
    - echo "Build stage finished"

deploy_sle15sp5:
  variables:
    LIBVIRT_VER: "9.0.0"
    SUSE_VER: "sle15sp5"
  tags:
    - sle15sp5
  stage: deploy
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH =~ /.*-sle15sp5/
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /.*-sle15sp5/
  script:
    - echo "Starting deploy stage for SLE15 SP5"
    - cd $CI_PROJECT_DIR
    - echo "rpm/deploy.sh $LIBVIRT_VER $SUSE_VER $PACKAGE_WORKSPACE $CI_PROJECT_DIR"

test_sle15sp5:
  tags:
    - sle15sp5
  stage: test
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH =~ /.*-sle15sp5/
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /.*-sle15sp5/
  script:
    - echo "Starting test stage for SLE15 SP5"
    - echo "Finishing test stage for SLE15 SP5"
